"""GitHub PR creation - creates a pull request after all tasks complete.

Requires: gh CLI (GitHub CLI) installed and authenticated.
"""

from __future__ import annotations

import asyncio
import logging
import subprocess

logger = logging.getLogger("ralph")


def is_gh_available() -> bool:
    """Check if the GitHub CLI is installed."""
    try:
        r = subprocess.run(["gh", "--version"], capture_output=True, timeout=5)
        return r.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


async def create_pull_request(
    workspace_dir: str,
    title: str,
    body: str,
    branch: str = "",
    base: str = "main",
) -> str | None:
    """Create a GitHub PR. Returns the PR URL or None on failure.

    Prerequisites:
    - gh CLI installed and authenticated
    - Remote repo configured
    - Changes committed and pushed
    """
    if not is_gh_available():
        logger.warning("gh CLI not available, skipping PR creation")
        return None

    # Push the branch first
    if branch:
        push_result = subprocess.run(
            ["git", "push", "-u", "origin", branch],
            cwd=workspace_dir, capture_output=True, text=True,
        )
        if push_result.returncode != 0:
            logger.warning("git push failed: %s", push_result.stderr[:200])
            return None

    try:
        proc = await asyncio.create_subprocess_exec(
            "gh", "pr", "create",
            "--title", title,
            "--body", body,
            "--base", base,
            cwd=workspace_dir,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=30)

        if proc.returncode == 0:
            pr_url = stdout.decode().strip()
            logger.info("PR created: %s", pr_url)
            return pr_url
        else:
            logger.warning("PR creation failed: %s", stderr.decode()[:200])
            return None

    except asyncio.TimeoutError:
        logger.warning("PR creation timed out")
        return None
    except Exception as e:
        logger.warning("PR creation error: %s", e)
        return None


def generate_pr_body(
    project_name: str,
    tasks_completed: list[dict],
    total_cost: float,
    total_tests: int,
) -> str:
    """Generate a PR description from the completed tasks."""
    lines = [
        "## Summary",
        f"Autonomous coding session for **{project_name}**.",
        "",
        "## Tasks Completed",
    ]

    for t in tasks_completed:
        lines.append(f"- **{t['id']}**: {t['title']}")

    lines.extend([
        "",
        "## Metrics",
        f"- Tasks: {len(tasks_completed)}",
        f"- Tests: {total_tests}",
        f"- Cost: ${total_cost:.2f}",
        "",
        "## Test Plan",
        "- [ ] All generated tests pass (`pytest tests/ -v`)",
        "- [ ] Manual review of generated code",
        "- [ ] No regressions in existing tests",
        "",
        "_Generated by [Ralph Loop](https://github.com/satvik/autonomous-coding-ralph-loop)_",
    ])

    return "\n".join(lines)
